language: go
go:
- 1.15
services:
- docker
env:
  global:
  - secure: "R4BS8u2baA8HnawuHE0fFYk/wGtcctDKICb/bWR0MKTp4OJ1DiCakM1BrwtLit3amUtCg5SWnbi5rvIbclXV/iW2P+ujDs8/COxDT2pfDHshTS+2TQY2UTzisACT9hOCjv5IdudqIs/tPPWFbRdKtYY6IbNglFPDKABRYEgh8ujwi5azW6Le4je7I3NhH4e1H3ocM33XtvkkEWsMeu2cec885hsQMb877azbfH+W68r/HJJm3Nbqsd/wQs/085btDtqrqk59tfYVllhHi7ZG3pHevNHc8h3CBdLGiWpXP+a2apND9CMiK7z9puB4U/eK+A0N02EX4/pqJ14KqpenCIUoYQ3VGSX4xOlJ8kcAeW52UebKd61YAI1s/SE0fF8XP6brZGbRlISBaLWSVbMKGDrVCCUJMRmInFwXqQHnrVi+FTe39xiqqJ6VMZ0Wiz1r+biS/UTXjzikC20i/NmHAJuqqnPimIG61vzDx/ajYx22TRWW6Ug5RaFcI79aR1G6EkB2qRxrfpvnPOn9J/bxnO39i6WZXdNwwQ+iAeZiOUpR6//XwkYBhvdYUo50BfGtOT2XbuABPuHyftGSCH16lRgNiKaGLjZBBhHHAl4AqIQl8O3eGaiXjcIsPafwBahisSrl6P8MjDYbkZ8rGGUpzzofyQ06Z9Lsff/Dw9KOfW4="
  - secure: "WOHbCGgXMQiGSqM9ODwpmfQrqs33HXJHjH1dt/AeL+DMIQKZ3zyyqE2OFSkvr+EQHkx4KENLE9oLBwhnO63mHfRSVF4revMJUqViz5+pPDw2D51oiT9uPnpnosf8yPMJA7EtpEhXTUNt8I7tifj5FXe6TQ66POtOWliNaD40AibffX6JlxXzrfnOAir0vHmry+VnfSZuNDU40D3JZqPkABDMY0NOEGn+IpscaPS045lD3H+oWsVatty0XnPJOTiSSTAHh4AnbEot2N3FZ568+qdaAVk/MgVHh/6MDxP16YiNGPpNQWLEtgFU/FVGJywE/ejeoyNtuifHSgZDBPlH0f4z5Q5R7MeGvjtFuPQ+52FvbDjJd38isAr9xJCNO5JNrqnwcqZyQpYcxRkNZUpBar5g3nAWMdHsh2yKyBc5fEIu+53KJF8ENIN3Mn/XoWrj2gCqizyIIiMqqatz1Wa4EZHiPw/SlfMX0o6QXRBDfpbAe/5/SGdmFRBOLSRunSiKC6Gu0jUPktcqB4iQn1JE3v2dTG3MexA2MS/waDJRBKjvs/NzroMyHXGutI+6124m2f+Oj+9Q+YtpNd+0u9XqiJxk1/MrBh3voNxYjmxEqB8AF7zWJJaeHZCkueFcYBnJoXOsKnX0mbanR6rKdCiZ7fViekPqkNQeqfWK5IIFvqk="
jobs:
  include:
  - stage: test
    name: Run tests
    script:
    - make test
  - stage: build
    name: Build
    script:
    - make build
    - make image
    deploy:
      provider: releases
      skip_cleanup: true
      name: tfsec $TRAVIS_TAG
      file:
      - bin/darwin/tfsec-darwin-amd64
      - bin/linux/tfsec-linux-amd64
      - bin/windows/tfsec-windows-amd64.exe
      api_key:
        secure: "gnFbED/JgihbV3zO6BgMj1YY7W+LsMHgVbamdMXcwwI4+9ouUa87D3vXIBpbAPUK7/aNmBeqDhXYX9grpy1gUAkmfPXhqH3zuOFnSiwoGFkZe0coRzZiqNU/pzxB4sZDihDLvk/E8btdNmNwSz6JkYvSbmGfN+b6M1N6Ico/kocV/XPYjfhGcArpngJ0CdbP656ixVo+s9ogwQUI3fNeelX0ppBjj1X8HZMMyLPuDvAsslWn0lb4rTqvpJitqcPaff8VRtnrQExNm5dVhEo03t+zYzPt+6EFhhx2K+dPpnWcDfl6yw7E+mKeN/LZIvGx+9pTQ3I3sclvtQ/COQ2WQn3z5wa5h9D/fsKBS/WxYMx8jWU/TcBeNpLDZhJcILwtYISKi9KfxY8Mr4FcHa+3Zl+uGZHWdbVgx8VR7SdDPi+H7QKcNrMJr7HAE/bHYNocE9qygWWpzGupznYX9RCNRhT51ebSlC497ZPugAkEdlax3yZcNf9CRXrCMLguJhoU3lOK8FyKt8Vvr/OTgbdJT7f440N5U3ETn4d+McZTIH0Gu71DfUAivixCVM2Ex6lvzcms1ZTwSsZMs888eI7mnStJoBS2vNo5AjR2jF0/FlCAjQRl9xUY+mCcRDrsQE2mFpqst4DvBhyYqzXrAiAzemcgtCVsmWpYkd9QrpBde04="
      on:
        repo: tfsec/tfsec
        tags: true
  - stage: publish image
    name: Publish Docker image
    if: tag IS NOT blank
    before_script:
    - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    script:
    - make image
    - make push-image
